# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published,  workflow_dispatch]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Bump package version to ${{ github.ref_name }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        pip install bump2version==1.0.1
        # Here we don't use ${{ github.ref_name }} since github action variables can't do sed/cut/slicing
        # Remove leading 'v' from the tag name
        bump2version --new-version ${GITHUB_REF_NAME#v} minor
        # must supply either patch minor or major see https://github.com/c4urself/bump2version/issues/244
        # but it's an ignored argument argument
        git show
        git push